@base_url = http://localhost:8080/api/techchefs

POST http://localhost:8080/api/authenticate HTTP/1.1
Content-Type: application/json

{
  "username": "user",
  "password": "root"
}

### List All Recipes

GET {{base_url}}/RecipeService HTTP/1.1

### List All Ingredients

GET {{base_url}}/IngredientService HTTP/1.1

### Get Recipe

GET {{base_url}}/(id) HTTP/1.1

### Get Ingredient

GET {{base_url}}/RecipeService/(ingredient) HTTP/1.1

### Add Recipe

POST {{base_url}}/RecipeService HTTP/1.1
Content-Type: application/json

{
  "name": "PB&J",
  "Description": "Peanut Butter and Jelly"
}

### Add Ingredient

POST {{base_url}}/IngredientService HTTP/1.1
Content-Type: application/json

{
  "name": "Peanut Butter",
  "parent_id": 1,
  "contains_dairy": 1,
  "nut_based": 1
}

### Update Recipe

PUT {{base_url}}/RecipeService/1 HTTP/1.1
Content-Type: application/json

{
  "name": "PB&J",
  "Description": "Peanut Butter and Jelly update"
}

### Update Ingredient

PUT {{base_url}}/IngredientService/1 HTTP/1.1
Content-Type: application/json

{
  "name": "PB"
}

### Delete Recipe

DELETE {{base_url}}/RecipeService/1 HTTP/1.1

### Delete Ingredient

DELETE {{base_url}}/IngredientService/1 HTTP/1.1
